In [1]:
import pandas as pd
df = pd.read_csv("All Files\ds1.csv")

In [2]:
pd.read_csv("All Files\ds1.csv", header=None)

,0,1,2,3,4,5,6,7,8,9,10
0,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Salary
1,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,168251
2,940761,Ms.,Brenda,S,Robinson,NaN,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,51063
3,428945,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,50155
4,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,180294
...,...,...,...,...,...,...,...,...,...,...,...
96,639892,Mr.,Jose,K,Hill,M,jose.hill@hotmail.com,Carlos Hill,Anna Hill,Hayes,129774
97,704709,Dr.,Harold,Z,Nelson,M,harold.nelson@gmail.com,Richard Nelson,Pamela Nelson,Smith,156194
98,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,95673
99,392491,Mrs.,Theresa,R,Murphy,F,theresa.murphy@gmail.com,George Murphy,Jacqueline Murphy,Peterson,51015
100,495141,Drs.,Tammy,B,Young,F,tammy.young@comcast.net,Andrew Young,Brenda Young,Robinson,93650

In [7]:
df = pd.read_csv("All Files\ds1.csv",usecols=["Emp ID","First Name"]).head()
df

   Emp ID First Name
0  677509       Lois
1  940761     Brenda
2  428945        Joe
3  408351      Diane
4  193819   Benjamin

In [4]:
# pd.read_csv()
dfs = pd.read_csv("All Files\ds1.csv", chunksize=10)
for df in dfs:
    print(df)

   Emp ID Name Prefix First Name Middle Initial Last Name Gender  \
0  677509        Drs.       Lois              H    Walker      F
1  940761         Ms.     Brenda              S  Robinson    NaN
2  428945         Dr.        Joe              W  Robinson      M
3  408351        Drs.      Diane              I     Evans      F
4  193819         Mr.   Benjamin              R   Russell      M
5  499687         Mr.    Patrick              F    Bailey      M
6  539712         Ms.      Nancy              T     Baker      F
7  380086        Mrs.      Carol              V    Murphy      F
8  477616        Hon.    Frances              B     Young      F
9  162402        Hon.      Diana              T  Peterson      F

                         E Mail      Father's Name       Mother's Name  \
0       lois.walker@hotmail.com      Donald Walker        Helen Walker
1     brenda.robinson@gmail.com   Raymond Robinson       Judy Robinson
2        joe.robinson@gmail.com     Scott Robinson  Stephanie Robinson
3         diane.evans@yahoo.com        Jason Evans      Michelle Evans
4  benjamin.russell@charter.net    Gregory Russell   Elizabeth Russell
5        patrick.bailey@aol.com       Ralph Bailey        Laura Bailey
6            nancy.baker@bp.com        Scott Baker          Judy Baker
7        carol.murphy@gmail.com      Eugene Murphy    Katherine Murphy
8       frances.young@gmail.com         Fred Young       Lillian Young
9  diana.peterson@hotmail.co.uk  Jonathan Peterson  Christina Peterson

  Mother's Maiden Name  Salary
0                Lewis  168251
1                Perry   51063
2               Taylor   50155
3                Allen  180294
4               Nelson  117642
5            Henderson   72305
6               Thomas   98189
7             Peterson   60918
8                 Diaz  121587
9                 Ross   43010
    Emp ID Name Prefix First Name Middle Initial  Last Name Gender  \
10  231469         Mr.      Ralph              L     Flores      M
11  153989       Prof.       Jack              C  Alexander      M
12  386158        Mrs.    Melissa              Q       King      F
13  301576        Hon.      Wayne              G     Watson      M
14  441771        Mrs.     Cheryl              O      Scott      F
15  528509        Hon.      Paula              G       Diaz      F
16  912990         Mr.     Joshua              T    Stewart      M
17  214352         Ms.    Theresa              G        Lee      F
18  890290        Hon.      Julia              S      Scott      F
19  622406         Mr.     Thomas              Q      Lewis      M

                      E Mail     Father's Name     Mother's Name  \
10    ralph.flores@yahoo.com      Terry Flores   Michelle Flores
11  jack.alexander@gmail.com  Samuel Alexander  Sharon Alexander
12  melissa.king@comcast.net       Philip King        Maria King
13    wayne.watson@gmail.com     Ronald Watson   Margaret Watson
14    cheryl.scott@gmail.com     Richard Scott        Lois Scott
15      paula.diaz@gmail.com         Alan Diaz      Kathryn Diaz
16   joshua.stewart@yahoo.ca      Todd Stewart    Martha Stewart
17     theresa.lee@gmail.com          John Lee       Rebecca Lee
18     julia.scott@apple.com    Lawrence Scott         Amy Scott
19    thomas.lewis@gmail.com        Ryan Lewis        Lois Lewis

   Mother's Maiden Name  Salary
10                Moore  118457
11               Walker   82965
12                White  166892
13                Hayes   92758
14               Watson   92220
15               Powell  152654
16                Jones  184896
17               Turner  197537
18                 King  141518
19                Price   73862
    Emp ID Name Prefix First Name Middle Initial Last Name Gender  \
20  979607         Ms.      Carol              J   Edwards      F
21  969580       Prof.    Matthew              L    Turner      M
22  426038        Hon.       Joan              C   Stewart      F
23  388642        Mrs.       Ruby              R    Rogers      F
24  560455         Ms.    Carolyn              V     Hayes      F
25  477253        Mrs.       Anne              L   Russell      F
26  263480        Hon.     Daniel              K    Cooper      M
27  683826         Mr.      Roger              L   Roberts      M
28  474599        Drs.      Maria              W    Walker      F
29  335732         Ms.     Brenda              M    Butler      F

                         E Mail    Father's Name      Mother's Name  \
20        carol.edwards@msn.com    Shawn Edwards      Susan Edwards
21     matthew.turner@gmail.com      Jose Turner       Kathy Turner
22       joan.stewart@yahoo.com  Charles Stewart      Julia Stewart
23        ruby.rogers@gmail.com    Ronald Rogers      Teresa Rogers
24  carolyn.hayes@hotmail.co.uk      Jimmy Hayes         Sara Hayes
25         anne.russell@ibm.com    Jimmy Russell  Stephanie Russell
26      daniel.cooper@yahoo.com     Louis Cooper       Julie Cooper
27      roger.roberts@gmail.com  Antonio Roberts  Katherine Roberts
28   maria.walker@microsoft.com     Ralph Walker      Teresa Walker
29      brenda.butler@gmail.com   Phillip Butler       Joyce Butler

   Mother's Maiden Name  Salary
20                 Gray   93967
21                  Cox   52237
22              Collins  111673
23            Alexander  160623
24               Foster   42005
25           Richardson  103160
26               Murphy  153790
27               Brooks  129625
28               Brooks   48944
29               Thomas   60508
    Emp ID Name Prefix First Name Middle Initial Last Name Gender  \
30  329752        Hon.    Lillian              X     Brown      F
31  893212         Ms.        Amy              B    Howard      F
32  621833         Mr.    Gregory              X   Edwards      M
33  456747         Mr.        Roy              Z   Griffin      M
34  278556       Prof.    Richard              Y  Mitchell      M
35  333476        Hon.       Mary              P    Wilson      F
36  218791         Mr.      Aaron              N     Price      M
37  134841         Ms.      Donna              R     Brown      F
38  726264        Hon.       Carl              N   Collins      M
39  766610         Ms.      Joyce              E   Jenkins      F

                          E Mail     Father's Name    Mother's Name  \
30         lillian.brown@aol.com        Gary Brown   Virginia Brown
31            amy.howard@aol.com      James Howard  Virginia Howard
32   gregory.edwards@outlook.com      Jose Edwards    Helen Edwards
33         roy.griffin@yahoo.com  Benjamin Griffin    Wanda Griffin
34  richard.mitchell@verizon.net    Peter Mitchell  Andrea Mitchell
35     mary.wilson@sbcglobal.net     Robert Wilson  Jennifer Wilson
36            aaron.price@bp.com     Michael Price      Diana Price
37           donna.brown@aol.com        Adam Brown      Irene Brown
38        carl.collins@yahoo.com    Gerald Collins  Phyllis Collins
39         joyce.jenkins@aol.com    Edward Jenkins    Susan Jenkins

   Mother's Maiden Name  Salary
30                 Wood   67251
31              Collins  112715
32               Howard  169245
33              Simmons  170895
34               Flores  122226
35            Patterson  109394
36               Torres   54402
37                James  129836
38            Rodriguez  162159
39                Hayes  119321
    Emp ID Name Prefix First Name Middle Initial  Last Name Gender  \
40  923947         Ms.       Mary              G     Bryant      F
41  227922        Hon.     Amanda              M     Hughes      F
42  265813        Hon.       Jack              E   Campbell      M
43  247137         Mr.       Alan              E     Rivera      M
44  407061         Ms.  Elizabeth              Q    Jackson      F
45  226714        Drs.      Nancy              L      Davis      F
46  702813         Mr.     Ernest              D   Martinez      M
47  524896         Ms.       Judy              Y  Hernandez      F
48  363065        Drs.      Nancy              L      Jones      F
49  879753        Mrs.     Pamela              X     Wright      F

                          E Mail    Father's Name      Mother's Name  \
40       mary.bryant@verizon.net    Joshua Bryant       Norma Bryant
41  amanda.hughes@rediffmail.com       Roy Hughes     Cynthia Hughes
42       jack.campbell@gmail.com  Philip Campbell     Wanda Campbell
43         alan.rivera@apple.com     Bobby Rivera    Jennifer Rivera
44     elizabeth.jackson@aol.com    Scott Jackson  Catherine Jackson
45           nancy.davis@ibm.com      Bruce Davis      Jessica Davis
46     ernest.martinez@gmail.com    Ryan Martinez   Beverly Martinez
47      judy.hernandez@gmail.com   Fred Hernandez   Pamela Hernandez
48         nancy.jones@gmail.com     Eugene Jones       Sandra Jones
49         pamela.wright@aol.com     Terry Wright       Debra Wright

   Mother's Maiden Name  Salary
40               Harris  155442
41               Bryant  114257
42               Watson  186280
43              Jackson  154810
44              Jackson   85420
45                Moore   94986
46                 Hill  172098
47                Evans  133332
48              Jenkins   61924
49             Williams  149262
    Emp ID Name Prefix First Name Middle Initial   Last Name Gender  \
50  958326         Mr.      Larry              T      Miller      M
51  447813        Mrs.        Ann              Q     Coleman      F
52  525955        Drs.       Judy              C    Gonzales      F
53  818384         Mr.      Peter              X  Washington      M
54  971640       Prof.   Clarence              A        Ross      M
55  253573         Ms.     Sharon              E       Lopez      F
56  904898        Drs.        Ann              Q      Cooper      F
57  515103         Ms.       Anne              A       Perez      F
58  491943        Mrs.      Nancy              P      Howard      F
59  750173         Mr.    Antonio              R     Roberts      M

                         E Mail       Father's Name    Mother's Name  \
50       larry.miller@shell.com      Russell Miller   Mildred Miller
51          ann.coleman@ibm.com      Harold Coleman     Tina Coleman
52      judy.gonzales@gmail.com      Kevin Gonzales  Sharon Gonzales
53      peter.washington@bp.com  Douglas Washington  Jean Washington
54      clarence.ross@apple.com         Arthur Ross      Louise Ross
55       sharon.lopez@gmail.com        Daniel Lopez      Susan Lopez
56    ann.cooper@exxonmobil.com       Harold Cooper   Mildred Cooper
57     anne.perez@sbcglobal.net       Douglas Perez      Doris Perez
58       nancy.howard@gmail.com      Gregory Howard   Mildred Howard
59  antonio.roberts@hotmail.com     Timothy Roberts    Diana Roberts

   Mother's Maiden Name  Salary
50                 Ward   97904
51               Walker  130014
52                Perez  149575
53            Henderson  173226
54           Washington  165272
55                Hayes  190139
56             Williams  182521
57               Bailey  114426
58               Flores  101553
59            Rodriguez  181646
    Emp ID Name Prefix   First Name Middle Initial Last Name Gender  \
60  687017         Ms.      Frances              P    Watson      F
61  241882         Ms.        Debra              G      Wood      F
62  758872         Mr.        Henry              Y   Jenkins      M
63  940922        Hon.      Melissa              X    Butler      F
64  917937         Mr.         Todd              H      Hall      M
65  917395        Hon.  Christopher              D    Nelson      M
66  183071        Drs.       Andrea              P    Garcia      F
67  316110         Mr.       Jeremy              I   Sanchez      M
68  293459         Mr.       Steven              J  Phillips      M
69  732017         Ms.      Cynthia              J   Ramirez      F

                            E Mail   Father's Name     Mother's Name  \
60      frances.watson@outlook.com     Adam Watson      Diana Watson
61          debra.wood@hotmail.com     Martin Wood      Theresa Wood
62       henry.jenkins@hotmail.com  Albert Jenkins   Beverly Jenkins
63      melissa.butler@hotmail.com   Robert Butler       Anne Butler
64             todd.hall@yahoo.com     Thomas Hall     Kathleen Hall
65      christopher.nelson@aol.com  Jeffrey Nelson    Cynthia Nelson
66           andrea.garcia@aol.com     Mark Garcia     Nicole Garcia
67      jeremy.sanchez@hotmail.com  Albert Sanchez  Patricia Sanchez
68     steven.phillips@hotmail.com  Jason Phillips   Gloria Phillips
69  cynthia.ramirez@btinternet.com  Walter Ramirez    Evelyn Ramirez

   Mother's Maiden Name  Salary
60                Jones   46945
61                Perry   84318
62               Murphy  102384
63              Jackson  167631
64               Morgan  163560
65              Sanders  190765
66               Howard   54179
67                 Ross  178847
68                Lewis   90108
69                Smith   90531
    Emp ID Name Prefix First Name Middle Initial   Last Name Gender  \
70  915638         Dr.      Jason              W    Anderson      M
71  478003        Hon.    Cynthia              X       White      F
72  951225         Ms.   Margaret              N      Brooks      F
73  883936         Mr.    Douglas              I      Flores      M
74  528673        Hon.       Paul              V      Watson      M
75  765850        Mrs.      Linda              R       Moore      F
76  262382         Ms.     Cheryl              O      Miller      F
77  870820         Ms.     Martha              G  Washington      F
78  806955         Mr.    William              G   Hernandez      M
79  325319        Hon.    Carolyn              F       Price      F

                              E Mail     Father's Name       Mother's Name  \
70          jason.anderson@gmail.com  Brandon Anderson      Julia Anderson
71           cynthia.white@gmail.com    Nicholas White     Katherine White
72         margaret.brooks@gmail.com     Johnny Brooks        Debra Brooks
73          douglas.flores@gmail.com     Justin Flores        Kathy Flores
74           paul.watson@hotmail.com       Carl Watson         Anna Watson
75             linda.moore@gmail.com      Howard Moore         Diana Moore
76        cheryl.miller@ntlworld.com     Gerald Miller    Christine Miller
77         martha.washington@aol.com   Todd Washington  Carolyn Washington
78  william.hernandez@rediffmail.com   Peter Hernandez   Deborah Hernandez
79           carolyn.price@yahoo.com       Kevin Price      Patricia Price

   Mother's Maiden Name  Salary
70                Baker   76636
71               Turner  186200
72             Robinson   43867
73              Ramirez  181793
74              Bennett  145235
75                Smith  113256
76             Mitchell   64143
77                 Reed  116629
78                Jones   73734
79             Williams   48736
    Emp ID Name Prefix First Name Middle Initial   Last Name Gender  \
80  623253        Mrs.       Ruby              Q     Stewart      F
81  225925         Mr.       Paul              D      Cooper      M
82  761821         Mr.     Ernest              G  Washington      M
83  400173         Ms.    Dorothy              K     Edwards      F
84  802554         Mr.       Ryan              V   Alexander      M
85  476433         Ms.    Lillian              N    Mitchell      F
86  533952         Ms.      Kelly              R       Adams      F
87  623929       Prof.      Jimmy              R      Howard      M
88  844177         Ms.   Margaret              T       Allen      F
89  212893         Ms.      Janet              Y   Henderson      F

                           E Mail      Father's Name        Mother's Name  \
80         ruby.stewart@gmail.com       Paul Stewart        Paula Stewart
81          paul.cooper@gmail.com    Nicholas Cooper         Helen Cooper
82      ernest.washington@msn.com  Johnny Washington   Shirley Washington
83  dorothy.edwards@hotmail.co.uk     Dennis Edwards        Betty Edwards
84       ryan.alexander@shell.com  William Alexander  Elizabeth Alexander
85       lillian.mitchell@shaw.ca     Harry Mitchell       Marie Mitchell
86             kelly.adams@bp.com         Eric Adams         Janice Adams
87         jimmy.howard@yahoo.com    Nicholas Howard      Patricia Howard
88       margaret.allen@gmail.com      Michael Allen          Karen Allen
89   janet.henderson@ntlworld.com    Jerry Henderson      Julie Henderson

   Mother's Maiden Name  Salary
80              Jackson  174774
81                 Hill   73526
82               Harris  176675
83               Howard  179017
84                 Gray  106628
85               Murphy  149878
86               Brooks   51878
87                Hayes  120631
88               Morris  180107
89               Cooper  114481
    Emp ID Name Prefix First Name Middle Initial Last Name Gender  \
90  185032         Mr.     Eugene              D     Perez      M
91  867084         Ms.    Deborah              E     Smith      F
92  969964        Hon.     Janice              S    Parker      F
93  158666         Ms.    Rebecca              A   Stewart      F
94  489424         Dr.    Phillip              F     White      M
95  639892         Mr.       Jose              K      Hill      M
96  704709         Dr.     Harold              Z    Nelson      M
97  461593         Ms.     Nicole              O      Ward      F
98  392491        Mrs.    Theresa              R    Murphy      F
99  495141        Drs.      Tammy              B     Young      F

                         E Mail   Father's Name      Mother's Name  \
90  eugene.perez@exxonmobil.com     Jimmy Perez         Lois Perez
91      deborah.smith@yahoo.com   Richard Smith        Diana Smith
92      janice.parker@yahoo.com     Paul Parker       Alice Parker
93    rebecca.stewart@gmail.com   Roger Stewart      Carol Stewart
94      phillip.white@gmail.com    Harold White      Frances White
95        jose.hill@hotmail.com     Carlos Hill          Anna Hill
96      harold.nelson@gmail.com  Richard Nelson      Pamela Nelson
97        nicole.ward@yahoo.com      Ralph Ward         Julia Ward
98     theresa.murphy@gmail.com   George Murphy  Jacqueline Murphy
99      tammy.young@comcast.net    Andrew Young       Brenda Young

   Mother's Maiden Name  Salary
90                 Hall  122950
91              Bennett   52767
92                Perez  147641
93                  Cox  160043
94               Carter  181774
95                Hayes  129774
96                Smith  156194
97                  Lee   95673
98             Peterson   51015
99             Robinson   93650